twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form/custom_errors.html.twig'
    globals:
        task_service: '@App\Service\TaskService'

when@test:
    twig:
        strict_variables: true
